version: "420"

services:

  frontend:
    build: ./client
    container_name: frontend-container
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mern-network

  backend:
    build: ./server
    container_name: backend-container
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongo-db
    networks:
      - mern-network

  mongo-db:
    container_name: mongo-db
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /home/rajat/Desktop/mongo-backup:/data/db
    
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
