version: "1"

services:

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mern-network

  backend:
    build: ./server
    container_name: backend
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - database
    networks:
      - mern-network

  database:
    container_name: mongo-db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /home/rajat/Desktop/mongo-backup:/data/db
    command: ["mongod", "--bind_ip", "0.0.0.0", "--config", "/etc/mongod.conf"]
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
    
